#!/usr/bin/env node
/**
 * Generates src/styles/tokens.css and src/styles/tokens.generated.ts
 * from design/figma-tokens.json.
 *
 * Do NOT hand-edit the outputs. Run `npm run tokens` after editing
 * the source JSON. This script runs automatically via `predev` and
 * `prebuild` hooks in package.json.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const tokensPath = path.resolve(__dirname, "../../design/figma-tokens.json");
const cssOut = path.resolve(__dirname, "../src/styles/tokens.css");
const tsOut = path.resolve(__dirname, "../src/styles/tokens.generated.ts");

if (!fs.existsSync(tokensPath)) {
  console.error(`[tokens] missing ${tokensPath}`);
  process.exit(1);
}

const tokens = JSON.parse(fs.readFileSync(tokensPath, "utf8"));

// ---- helpers ----
const kebab = (s) =>
  s
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/_/g, "-")
    .toLowerCase();

const flattenColors = (obj, prefix = "color") => {
  const out = {};
  for (const [group, entries] of Object.entries(obj)) {
    for (const [name, def] of Object.entries(entries)) {
      out[`--${prefix}-${kebab(group)}-${kebab(name)}`] = def.value;
    }
  }
  return out;
};

const pickValue = (obj) => {
  const out = {};
  for (const [k, v] of Object.entries(obj)) {
    out[k] = v.value;
  }
  return out;
};

// ---- collect vars ----
const colorVars = flattenColors(tokens.color);
const radiusVars = Object.fromEntries(
  Object.entries(tokens.radius).map(([k, v]) => [`--radius-${kebab(k)}`, v.value])
);
const spacingVars = Object.fromEntries(
  Object.entries(tokens.spacing).map(([k, v]) => [`--space-${kebab(k)}`, v.value])
);
const fontSizeVars = Object.fromEntries(
  Object.entries(tokens.fontSize).map(([k, v]) => [`--fs-${k}`, v.value])
);
const fontWeightVars = Object.fromEntries(
  Object.entries(tokens.fontWeight).map(([k, v]) => [`--fw-${kebab(k)}`, String(v.value)])
);
const letterSpacingVars = Object.fromEntries(
  Object.entries(tokens.letterSpacing).map(([k, v]) => [`--tracking-${kebab(k)}`, v.value])
);
const blurVars = Object.fromEntries(
  Object.entries(tokens.backdropBlur).map(([k, v]) => [`--blur-${kebab(k)}`, v.value])
);
const shellVars = Object.fromEntries(
  Object.entries(tokens.shell).map(([k, v]) => [`--shell-${kebab(k)}`, v.value])
);
const fontFamilyVars = Object.fromEntries(
  Object.entries(tokens.fontFamily).map(([k, v]) => [
    `--ff-${kebab(k)}`,
    v.value.map((f) => (f.includes(" ") ? `"${f}"` : f)).join(", "),
  ])
);

const allVars = {
  ...colorVars,
  ...radiusVars,
  ...spacingVars,
  ...fontSizeVars,
  ...fontWeightVars,
  ...letterSpacingVars,
  ...blurVars,
  ...shellVars,
  ...fontFamilyVars,
};

// ---- write CSS ----
const cssLines = [
  "/* GENERATED by scripts/generate-tokens.mjs — do not edit by hand. */",
  "/* Source: design/figma-tokens.json */",
  "",
  ":root, [data-theme='dark'] {",
];
for (const [k, v] of Object.entries(allVars)) {
  cssLines.push(`  ${k}: ${v};`);
}
cssLines.push("}", "");
// Base body styles using tokens
cssLines.push(`html, body, #root {
  height: 100%;
  background: var(--color-background-base);
  color: var(--color-text-primary);
  font-family: var(--ff-body);
  font-size: var(--fs-14);
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
}
`);

fs.mkdirSync(path.dirname(cssOut), { recursive: true });
fs.writeFileSync(cssOut, cssLines.join("\n"));
console.log(`[tokens] wrote ${path.relative(process.cwd(), cssOut)}  (${Object.keys(allVars).length} vars)`);

// ---- write TS (for Tailwind to consume) ----
const themeExtend = {
  colors: Object.fromEntries(
    Object.keys(tokens.color).flatMap((group) =>
      Object.keys(tokens.color[group]).map((name) => [
        `${kebab(group)}-${kebab(name)}`,
        `var(--color-${kebab(group)}-${kebab(name)})`,
      ])
    )
  ),
  borderRadius: Object.fromEntries(
    Object.keys(tokens.radius).map((k) => [kebab(k), `var(--radius-${kebab(k)})`])
  ),
  spacing: Object.fromEntries(
    Object.keys(tokens.spacing).map((k) => [kebab(k), `var(--space-${kebab(k)})`])
  ),
  fontSize: Object.fromEntries(
    Object.keys(tokens.fontSize).map((k) => [k, `var(--fs-${k})`])
  ),
  fontWeight: Object.fromEntries(
    Object.keys(tokens.fontWeight).map((k) => [kebab(k), `var(--fw-${kebab(k)})`])
  ),
  letterSpacing: Object.fromEntries(
    Object.keys(tokens.letterSpacing).map((k) => [kebab(k), `var(--tracking-${kebab(k)})`])
  ),
  backdropBlur: Object.fromEntries(
    Object.keys(tokens.backdropBlur).map((k) => [kebab(k), `var(--blur-${kebab(k)})`])
  ),
  fontFamily: Object.fromEntries(
    Object.keys(tokens.fontFamily).map((k) => [kebab(k), [`var(--ff-${kebab(k)})`]])
  ),
};

const tsLines = [
  "// GENERATED by scripts/generate-tokens.mjs — do not edit by hand.",
  "// Source: design/figma-tokens.json",
  "",
  `export const themeExtend = ${JSON.stringify(themeExtend, null, 2)};`,
  "",
];
fs.writeFileSync(tsOut, tsLines.join("\n"));
console.log(`[tokens] wrote ${path.relative(process.cwd(), tsOut)}`);
